bedroom_choices = {
  '1':1,
  '2':2,
  '3':3,
  '4':4,
  }

price_choices = {
  '100':'$100',
  '200':'$200',
  '300':'$300',
  '400':'$400',
  '500':'$500',
  '600':'$600',
}

state_choices = {
        'AL': 'Alabama',
      	'AK':	'Alaska',
      	'AZ':	'Arizona',
        'AR':	'Arkansas',
      	'CA':	'California',
        'CO':	'Colorado',
	      'CT': 'Connecticut',
	      'DE':	'Delaware',
	      'FL':	'Florida',
	      'GA':	'Georgia',
        'ID':	'Idaho',
	      'IL':	'Illinois',
       	'IN':'Indiana',
	      'IA':	'Iowa',
	      'KS':'Kansas',
	      'KY':	'Kentucky',
	      'LA':'Louisiana',
	      'ME':'Maine',
	      'MD':'Maryland',
	      'MA':'Massachusetts',
	      'MI':	'Michigan',
	      'MN':'Minnesota',
	      'MS':'Mississippi',
	      'MO':'Missouri',
	      'MT':'Montana',
	      'NE':	'Nebraska',
	      'NV':'Nevada',
	      'NH':	'New Hampshire',
	      'NJ':'New jersey',
	      'NM':	'Newico',
	      'NY'	:'New york',
	      'NC':	'North Carolina',
	      'ND'	:'North dakota',
	      'OH'	:'Ohio',
	      'OK':	'Okla',
	      'OR'	:'Oregon',
	      'PA':	'Pennsylvania',
	      'RI'	:'Rhode Island',
	      'SC':	'south carolina',
	      'SD':	'South dakota',
	      'TN'	:'Tennessee',
	      'TX'	:'Texas',
	      'UT'	:'Utah',
	      'VT'	:'Vermont',
	      'VA'	:'Virginia',
	      'WA'	:'Washington',
	      'WV'	:'West virginia',
	      'WI'	:'Wisconsin',
	      'WY'	:'Wyoming',
       
       
}